#!/bin/sh
set -e

GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

if [ -n "$CI_WORKSPACE" ]; then
    OUTPUT_FILE="${CI_WORKSPACE}/tankgame Shared/GitCommit.swift"
else
    OUTPUT_FILE="$(dirname "$(pwd)")/tankgame Shared/GitCommit.swift"
fi

cat > "$OUTPUT_FILE" << EOF
//
//  GitCommit.swift
//  tankgame
//
//  Auto-generated by ci_post_clone.sh
//

import Foundation

struct GitCommit {
    static let hash: String = "$GIT_COMMIT"
}
EOF

echo "Generated GitCommit.swift with commit hash: $GIT_COMMIT"
